export const ADD_NEW_HISTORY = 'CALCULATOR/HISTORY_REDUCER/ADD_NEW_HISTORY';
export const CLEAR_HISTORY = 'CALCULATOR/HISTORY_REDUCER/CLEAR_HISTORY';
export const SET_HISTORY_BLOCK_VISIBILITY =
  'CALCULATOR/HISTORY_REDUCER/SET_HISTORY_BLOCK_VISIBILITY';
export const SET_HISTORY_FROM_SESSION_STORAGE =
  'CALCULATOR/HISTORY_REDUCER/SET_HISTORY_FROM_SESSION_STORAGE';
export const DELETE_HISTORY_ITEM = 'CALCULATOR/HISTORY_REDUCER/DELETE_HISTORY_ITEM';
