export const CHANGE_CURRENT_VALUE = 'CALCULATOR/CALCULATOR_REDUCER/CHANGE_CURRENT_VALUE';
export const DELETE_LAST_SYMBOL = 'CALCULATOR/CALCULATOR_REDUCER/DELETE_LAST_SYMBOL';
export const NULLIFY_VALUE = 'CALCULATOR/CALCULATOR_REDUCER/NULLIFY_VALUE';
export const SET_ERROR_VALUE = 'CALCULATOR/CALCULATOR_REDUCER/SET_ERROR_VALUE';
export const SET_CONTROL_PANEL_VISIBILITY =
  'CALCULATOR/CALCULATOR_REDUCER/SET_CONTROL_PANEL_VISIBILITY';
